# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    
    # - name: Deploy to EC2
    #   uses: appleboy/scp-action@master
    #   with:
    #     host: ${{ secrets.IP}}
    #     username: ${{ secrets.UNAME }}
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     source: build/
    #     target: /var/www/html/


    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: '${{ secrets.AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.AWS_AUTH_KEY }}'
          aws-region: us-east-1
    
    - name: Build & Deploy
      run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > binaya.pem && chmod 400 binaya.pem
          sleep 60
          sudo scp -o StrictHostKeyChecking=no -i binaya.pem -r /home/runner/work/CICD_react_static_Scp/CICD_react_static_Scp/build/  ubuntu@44.203.53.193:/var/www/html
          sudo chmod -R 700 /var/www/html/
